name: terraform

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: hashicorp/setup-terraform@v4
      with:
        terraform_wrapper: false
    - name: terraform validate
      run: terraform init && terraform validate
      env:
        AWS_DEFAULT_REGION: us-east-1
    - uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::278105230435:role/managed/terraform-aws-ec2-pricing
        aws-region: us-east-1
    - name: Run tests
      run: make test
